### ISSUE TITLE
Redis fails to record to persistence file

### ISSUE THREAD

**Issue by Pigrenok** [danitseitlin/redis-interval-sets#23] opened 2021-10-13 13:48 UTC
Hello!

First of all, I would like to say that you have created an amazing plugin!

I have encountered an issue with it though.

I have set up persistence with recording to rdb file. But when I create an interval set using the following command:

`iset.add genes gene1 0 10 gene2 11 20 gene3 21 30`

and then ask it to save database to persistence file, redis fails to do it. 

Because I have 
stop-writes-on-bgsave-error yes
in the configuration file, redis crashes with error 11. Full configuration is available here [redis.conf](https://github.com/danitseitlin/redis-interval-sets/files/7338565/redis.conf.txt)
I tested it with this option turned off and it still fails.

Full redis bug report is available here:
[bug_report.txt](https://github.com/danitseitlin/redis-interval-sets/files/7338546/bug_report.txt)

without creating any records with interval set (I tried simple key-value pairs using SET and tried sorted set using ZADD command), it saves perfectly fine, so, it should not be the issue with redis itself.

I need persistence as I need to shut down and restart redis server and I need to make sure that the persistence store is correctly recorded.

What do you think can be an issue?

Thanks.

**Comment by danitseitlin** [comment] 2022-02-10 16:52
@Pigrenok Hi, working on fixing it. This is a duplicate of #20

**Closed** 2022-03-02 07:29 UTC
